server:
  port: 8081
spring:
  application:
    name: registry-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true

jwt:
  access-token-expiration: 15m
  refresh-token-expiration: 7d
cookie:
  same-site: Lax
  path: /
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${REG_DB_URL}
    username: ${REG_DB_USERNAME}
    password: ${REG_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: false
  data:
    redis:
      host: ${REG_REDIS_HOST}
      port: ${REG_REDIS_PORT}
      password: ${REG_REDIS_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: "http://${REG_EUR_USERNAME}:${REG_EUR_PASSWORD}@${REG_EUR_HOST}:${REG_EUR_PORT}/eureka/"

encoder:
  secret: ${ENCODER_SECRET}
jwt:
  access-token-secret: ${ACCESS_TOKEN_SECRET}
  refresh-token-secret: ${REFRESH_TOKEN_SECRET}
cookie:
  domain: hanyahunya.com
  secure: true